[provisioning]
adapter = "hybrid"
nix_adapter = "home-manager"
allow_rcm_fallback = true

[profile.default]
modules = [
  "base",
  "homebrew",
  "nushell",
  "neovim",
  "mise",
  "go/mise",
  "node/mise",
  "python/mise",
  "rust/cargo",
]
